public class DisplayWrapperClass{

@AuraEnabled

public String matchDescription{get;set;}

@AuraEnabled

public String matchOfficials{get;set;}

@AuraEnabled

public String matchStatus{get;set;}

@AuraEnabled

public String playingTeams{get;set;}

@AuraEnabled

public String currentSummary{get;set;}

@AuraEnabled

public String seriesName{get;set;}

@AuraEnabled

public String matchType{get;set;}

@AuraEnabled

public String hostCountry{get;set;}

@AuraEnabled

public String teamAPlayers{get;set;}

@AuraEnabled

public String teamBPlayers{get;set;}

@AuraEnabled

public String teamAName{get;set;} 

@AuraEnabled

public String teamBName{get;set;}

@AuraEnabled

public String matchScore{get;set;}

@AuraEnabled

public String matchTimings{get;set;}

@AuraEnabled

public String team1Image{get;set;}

@AuraEnabled

public String team2Image{get;set;}

@AuraEnabled

public String striker1Image{get;set;}

@AuraEnabled

public String striker1Name{get;set;}

@AuraEnabled

public String striker1handstyle{get;set;}

@AuraEnabled

public String striker1position{get;set;}

@AuraEnabled

public String striker1ballfaced{get;set;}

@AuraEnabled

public String striker1runs{get;set;}

@AuraEnabled

public String striker2Image{get;set;}

@AuraEnabled

public String striker2Name{get;set;}

@AuraEnabled

public String striker2handstyle{get;set;}

@AuraEnabled

public String striker2position{get;set;}

@AuraEnabled

public String striker2ballfaced{get;set;}

@AuraEnabled

public String striker2runs{get;set;}

@AuraEnabled

public String bowlerImage{get;set;}

@AuraEnabled

public String bowlerName{get;set;}

@AuraEnabled

public String bowlerMaiden{get;set;}

@AuraEnabled

public String bowlerhandstyle{get;set;}

@AuraEnabled

public String bowlerOvers{get;set;}

@AuraEnabled

public String bowlerConceeded{get;set;}

@AuraEnabled

public String bowlerpace{get;set;}

@AuraEnabled

public String bowlerWickets{get;set;}

@AuraEnabled

public Integer showImages{get;set;}

}