public class Series4_CTRL {
    public Integer inputText1{get;set;}
      public set<integer> s1{get;set;}
    
   
    public void getprocess(){ 

         s1 = new set<Integer>();
        
        
       for(integer i = 1;i<inputText1;i++)
        { 
            if (math.mod(inputText1,i) == 0)
        {
           s1.add(i); 
           
        }

        
        
        }
         s1.add(inputText1);
      
    }}